#!/bin/sh

exec 2>~/bspwm.err

numlockx on
setxkbmap "us,ru" -option grp:caps_toggle

$LOCK_SCREEN

feh --bg-fill ~/IMG_2363_cropped.JPG
#perWindowLayoutD
#xcompmgr &
#wmname LG3D

bspc config focused_border_color red
bspc config window_gap 0
bspc monitor -d 'itmo$browser' 'itmo$email'

export PANEL_HEIGHT=15
export PANEL_FONT_FAMILY='DejaVu Sans Mono:size=9'

start-pulseaudio-x11 &
~/.config/bspwm/panel &
exec sxhkd
