#!/bin/sh

numlockx on
setxkbmap "us,ru" -option grp:caps_toggle

slimlock

feh --bg-fill ~/IMG_2363_cropped.JPG
perWindowLayoutD
xcompmgr &
wmname LG3D

bspc config focused_border_color red
bspc config window_gap 0
bspc monitor -d 'itmo$browser' 'itmo$email'

export PANEL_FIFO=/tmp/panel_fifo
export PANEL_HEIGHT=15
export PANEL_FONT_FAMILY='Droid Sans Mono:size=9'

~/.config/bspwm/panel &>~/panel.err &

exec sxhkd
