#!/bin/sh

. ./panel_colors

while read -r line ; do
    case $line in
        V*)
            volume="${line#?}"
            ;;
        N*)
            network="${line#?}"
            ;;
        S*)
            # clock output
            sys_infos="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
            ;;
        T*)
            # xtitle output
            title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            ;;
        L*)
            # keyboard layout
            layout="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
    esac
    printf "%s\n" "%{l}${title}%{r}| ${layout} | ${network} |${sys_infos}|" || exit
done
