# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  # Define on which hard drive you want to install Grub.
  boot.loader.grub = {
    device = "/dev/sda";
    extraEntries = ''
      menuentry "Windows 8" {
        chainloader (hd0,1)+1
      }
    '';
  };

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "usbhid" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  #boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a172ad5-e5af-4aa1-8b40-e5705691f242";
      fsType = "ext4";
    };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c5f7eb3d-acc9-41ce-a16b-082087e8f514";
    fsType = "ext4";
    options = [ "rw" ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/41ff1b4e-065e-4d12-aeca-75e650dd0440"; } ];

  services.xserver.videoDrivers = [ "nouveau" ];
  #services.xserver.videoDrivers = [ "nvidiaLegacy340" ];
  hardware.pulseaudio = {
    enable = true;
    package = pkgs.pulseaudioFull;
    extraConfig = "load-module module-switch-on-connect";
  };
  hardware.opengl.driSupport32Bit = true;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  services.xserver.synaptics.enable = true;
  services.logind.lidSwitch = "ignore";
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.
  networking.hostName = "tompe_laptop"; # Define your hostname.
  services.tor.enable = true;

  nix.maxJobs = lib.mkDefault 4;
}
