#!/bin/sh

numlockx on
setxkbmap "us,ru" -option grp:caps_toggle

$LOCK_SCREEN

feh --bg-fill ~/IMG_2363_cropped.JPG
perWindowLayoutD
xcompmgr &

bspc config focused_border_color red
bspc config window_gap 0
bspc monitor -d 'itmo$browser' 'itmo$email'

export PANEL_FIFO=/tmp/panel_fifo
export PANEL_HEIGHT=15
export PANEL_FONT_FAMILY='Droid Sans Mono:size=9'
sxhkd &

exec panel &>$HOME/panel.err
